name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH Key
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_key
          chmod 600 ssh_key
          eval "$(ssh-agent -s)"
          ssh-add ssh_key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Deploy to VPS
        run: |
          scp -r ./* root@api.wowtwinks.info:/api/twinkinfos
          ssh root@api.wowtwinks.info 'cd api/twinkinfos && npm install && pm2 restart twinkinfos'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
