name: Deploy to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create SSH directory and add private key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server key to known_hosts and authorized_keys
        run: |
          ssh-keyscan 158.69.28.205 >> ~/.ssh/known_hosts
          echo "$(cat ~/.ssh/id_rsa.pub)" >> ~/.ssh/authorized_keys
          # Ensure correct permissions for the SSH directory and files
          - run: chmod 700 ~/.ssh && chmod 600 ~/.ssh/*

      - name: Deploy to VPS
        run: |
          echo "Starting deployment..."
          scp -r ./* root@158.69.28.205:/api/twinkinfos
          ssh root@158.69.28.205 'cd /api/twinkinfos && npm install && pm2 restart twinkinfos'
          echo "Deployment completed."
